### ISSUE TITLE
Help understanding the test setup

### ISSUE THREAD

**Issue by xeoncross** [NetsydeMiro/leancrypt#3]
You have a great start to a library here and I have gone ahead and forked it to start working on adding [signing to the supported operations](https://github.com/Xeoncross/leancrypt/commit/20c04a4663ba585bafa956a4d66704696ef52416).

However, I tried to split the LeanCrypt.ts file into multiple files and got lost trying to keep the unit tests and coverage spec working. I started by manually including the [chai and LeadCrypt libraries inside the spec](https://github.com/Xeoncross/leancrypt/blob/master/specs/LeanCrypt.specs.ts#L4-L6) but I'm getting a totally empty nyc/puppetter report (below).

Do you have any pointers on the way you setup this project?

![Screen Shot 2020-09-28 at 8 50 37 PM](https://user-images.githubusercontent.com/56460/94503589-6be41d00-01cc-11eb-960d-1cbe662f4d02.png)

**Comment by NetsydeMiro** [comment]
Hi there, 

Thanks for your interest in the library; I hope you find some use for it.  

Unfortunately, it's been some time since I've looked at the code, and I do remember having to hack about a bit to get typescript, mocha, puppeteer, and istanbul to play even semi-nicely together.  Updating the project to be broken into separate files is a good idea, and I'd planned to take it on at some point, but getting compilation and the test harness to work with multiple files was giving me issues, so I'd tentatively started and left it as a single file.  

Unfortunately I don't have the time at present to invest in updating the codebase to a more modern and intuitive test setup, but I do hope to return to it at some point in the future.  If you make any more progress than feel free to keep me posted, and I'll do the same once I get back to looking into browser-based encryption.  

My only recommendation at present would be to try incorporating your changes into the single file structure and see if it works as expected.  Splitting into multiple files may need to be done gradually, and separately from any functional changes.  You may or may not need to make updates to test/index.html and tsconfig.test.json in order for the browser tests to work.  

Good luck!

**Comment by xeoncross** [comment]
Thank you for your response. I ultimately [gave up on](https://github.com/NetsydeMiro/leancrypt/compare/master...Xeoncross:master#diff-0305747ac7bc325e9f20e72496d24516) getting namespaces or modules to work well with multiple files (Javascript is so hacky still) and moved back to a single file for now. 

Thank you for the scaffolding you setup, there aren't many projects with a development env like this ready to go. Modern Typescript is not my primary language, so finding resources is a bit harder, but working so far.
